site_name: Manos Dev Wiki
site_url: https://manos-software.github.io
site_description: Information for developers working within the Manos ecosystem.

repo_url: https://github.com/manos-software/devwiki
edit_uri: blob/main/docs/

# Configuration
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: manos-software
      repo: devwiki

# Page Tree
nav:
  - Home: index.md
  - Developer Roadmaps:
    - Delphi: roadmaps/delphi.md
    - .NET: roadmaps/dotnet.md
    - Java: roadmaps/java.md
    - PHP: roadmaps/php.md
    - Progress: roadmaps/progress.md
    - Python: roadmaps/python.md
    - Rust: roadmaps/rust.md
    - Swift: roadmaps/swift.md
    - TypeScript & JavaScript: roadmaps/typescript.md